In [1]:
import torch
import torch.nn as nn
import torch.distributions as dist

Esayons le modèle de GFlowNet continu. Le modèle utilisé est le modèle model/gflownet.py

In [2]:
from models.gflownet import GFlowNet

initialisons le modèle

In [3]:
state_dim = 3
action_dim = 3
n_steps = 4
model = GFlowNet(state_dim=state_dim, action_dim=action_dim, n_steps=n_steps)

Génération d'un batch aléatoire

In [4]:
batch_size = 5
states = torch.rand(batch_size, state_dim)

Tester la méthode sample_action du modèle

In [5]:
actions, log_probs = model.sample_action(states, action_dim=action_dim)

#Afficher les résultats
print("États initiaux :")
print(states)
print("\nActions générées :")
print(actions)
print("\nLog-probabilités des actions :")
for i, log_prob in enumerate(log_probs):
    print(f"Step {i + 1}:")
    print(log_prob)

États initiaux :
tensor([[0.4432, 0.0798, 0.0791],
        [0.3449, 0.4610, 0.5511],
        [0.8393, 0.3597, 0.4959],
        [0.1319, 0.2428, 0.7552],
        [0.2584, 0.5522, 0.7722]])

Actions générées :
tensor([[[0.1967, 0.5317, 0.2716],
         [0.4436, 0.5407, 0.0158],
         [0.1138, 0.8730, 0.0132],
         [0.5781, 0.3959, 0.0260]],

        [[0.6624, 0.2655, 0.0721],
         [0.4701, 0.2911, 0.2389],
         [0.2472, 0.3152, 0.4376],
         [0.7274, 0.0810, 0.1916]],

        [[0.7415, 0.0048, 0.2537],
         [0.0824, 0.0050, 0.9126],
         [0.2679, 0.6788, 0.0534],
         [0.8442, 0.0942, 0.0617]],

        [[0.7167, 0.2413, 0.0420],
         [0.1353, 0.7635, 0.1013],
         [0.2785, 0.2441, 0.4774],
         [0.1990, 0.2542, 0.5467]],

        [[0.1772, 0.1948, 0.6280],
         [0.0146, 0.1613, 0.8241],
         [0.5865, 0.2362, 0.1773],
         [0.0786, 0.0142, 0.9072]]])

Log-probabilités des actions :
Step 1:
tensor([0.3689, 0.5836, 1.1094, 0.7680, 0.